{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hello-kubernetes.name" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.ingress.rewritePath }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
        - pathType: Prefix
          path: "{{ required "ingress.PathPrefix is required when using ingress.enabled!" .Values.ingress.pathPrefix }}(/|$)(.*)"
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
{{- end }}
